#cloud-config
packages:
  - nginx
  - curl
runcmd:
  - systemctl enable nginx
  - systemctl start nginx
  - curl -fLo /opt/server https://github.com/thecjharries/dso-dojo-2022-11/releases/download/0.0.1/server
